# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: en-US
title: "Ariel Lucki"
subtitle: ""
name: "Ariel Lucki"
logo: "/assets/images/png/lion_white.png"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog. Not much to see here for the time being, but
  thanks for the visit! Please drop by later ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: anlucki
linkedin_username: anlucki
instagram_username: anlucki

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.20.1
minimal_mistakes_skin: dark
search: true
include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-email-protect
  - jekyll-paginate-v2

whitelist:
  - "jekyll-paginate-v2"
  - "jekyll-email-protect"

pagination:
  enabled: true
  per_page: 3
  permalink: ‘/page/:num/’
  title: ’ - page :num’
  limit: 1
  sort_field: ‘date’
  sort_reverse: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: false
      share: false
      related: false
      show_date: true
      read_time: true
      classes: wide

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name: "Ariel Lucki"
  avatar: "/assets/images/jpg/profile.jpg"
  location: "Buenos Aires, Argentina"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anlucki"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anlucki"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/anlucki"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anlucki"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anlucki"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/anlucki"

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
